### ISSUE TITLE
软件建议

### ISSUE THREAD

**Issue by wqwangwei** [ZzzM/CalendarX#10]
第一个是状态栏图标显示,风格有点迥异与系统有点不兼容感,还有就是希望能多几个选项,有周显示与日期显示.
第二个是时间是否可以显示到日历下方,单独显示事件内容.
建议参考一下 "Dato for mac" 软件的显示效果

**Comment by ZzzM** [comment]
可在设置-菜单栏样式中修改，支持日期样式，还可以通过拖拽编辑日期格式

**Comment by wqwangwei** [comment]
> 可在设置-菜单栏样式中修改，支持日期样式，还可以通过拖拽编辑日期格式

怎么设置样式,能不能设置成下面这样

![20240220roe0oHdY](https://github.com/ZzzM/CalendarX/assets/18253949/7cf2763e-d9f5-42ff-acbe-beca9b46c0ce)

**Comment by ZzzM** [comment]
暂不支持这样的布局，感谢建议，后续会参考

**Comment by senlinmuvs** [comment]
建议嵌入桌面或通知中心

**Comment by ZzzM** [comment]
@senlinmuvs 
最新版本是支持小组件的，请自行设置
