### ISSUE TITLE
可能是一个bug

### ISSUE THREAD

**Issue by ldw4033** [ZzzM/CalendarX#11]
![Xnip-20240221105755](https://github.com/ZzzM/CalendarX/assets/5718303/0a10e388-f1a7-4085-a0f6-28b20451d490)
1处显示的是当前日期，2处显示的是昨天的日期，点击3后无反应

**Comment by dotSpecs** [comment]
我也遇到了这个问题，好像是每天前几次点开都是这样的

**Comment by amanlhw** [comment]
加一

**Comment by AlanBrian-z** [comment]
+1

**Comment by nanusl** [comment]
+1
合盖后，第二天打开，“今天”还是显示的昨天，必须点下<或>后，再点“今日”才能恢复

**Comment by ZzzM** [comment]
新版本已修复该问题，感谢各位反馈
