### ISSUE TITLE
透明背景色设置 磨砂玻璃质感设置 各元素颜色大小自定义 能不能添加本年度第几周的元素

### ISSUE THREAD

**Issue by yiletianya** [ZzzM/CalendarX#14]
感谢大神开发并开源这么好用的一款软件，欣喜之余，在使用之后还有一点小建议。
1.能否添加透明背景色设置滑块
2.能否添加背景色磨砂玻璃质感设置滑块
3.能否添加主题色各元素颜色自定义 ，以及文字大小，界面宽度高度设置的滑块调整。
4.可否在界面添加本年度第几周的信息元素（比如说6月1号是第22周）

**Comment by ZzzM** [comment]
感谢建议，后续版本可考虑添加该需求 `4.可否在界面添加本年度第几周的信息元素（比如说6月1号是第22周）`
