### ISSUE TITLE
请问如何定义显示农历?

### ISSUE THREAD

**Issue by Jonnyan404** [ZzzM/CalendarX#5]
像初一/初二/初三这种

**Comment by ZzzM** [comment]
你是指菜单栏吗？

**Comment by Jonnyan404** [comment]
> 目前不支持，菜单栏日期与时间显示这块的话，我还在重构，你是想显示农历日期，像“正月初一”这样的格式？

对的,最好  正月初一  能分成两部分,正月一部分,初一一部分.

**Comment by AlanBrian-z** [comment]
> 

大佬 ，什么时候会发新版本呢？

**Comment by ZzzM** [comment]
新版本已发布，可通过拖放来实现日历格式编辑

**Comment by Jonnyan404** [comment]
> 新版本已发布，可通过拖放来实现日历格式编辑

为啥自动更新和开机启动的按钮点不动呢?  点了没任何反应

**Comment by ZzzM** [comment]
正在修复

**Comment by Jonnyan404** [comment]
> @Jonnyan404 感谢反馈，已修复，麻烦更新

没问题了,感谢!
