### ISSUE TITLE
日程标注错误

### ISSUE THREAD

**Issue by insuns** [ZzzM/CalendarX#6]
如下图，日程标注的绿点错位了
![WX20230227-132627@2x](https://user-images.githubusercontent.com/50972555/221482103-12eb1dfd-7912-4b4c-8281-6b01d8dbf903.png)

系统：
芯片：Apple M1
macOS：13.2.1 (22D68)

**Comment by ZzzM** [comment]
已修复，麻烦更新

**Comment by insuns** [comment]
Thanks
