### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by viewsourc3** [ZzzM/CalendarX#7]
Installed this app on a M1 Pro, 13.2.1 (22D68). The app launches, as I can see it in the activity monitor, but there is no app window or icon in the task bar.

**Comment by viewsourc3** [comment]
It was bugged on my end.

**Comment by ZzzM** [comment]
CalendarX is a menubar app, you can find it in the menubar. like this
![snapshot](https://user-images.githubusercontent.com/10611210/224530988-4a0671ca-2c05-451d-9448-d2e3438a9c90.png)

**Comment by viewsourc3** [comment]
yes, thank you. It was a bug because of my system configuration. All good, thank you.
