### ISSUE TITLE
一个小建议，日期上的操作改进

### ISSUE THREAD

**Issue by oneCatZz** [ZzzM/CalendarX#9]
![CleanShot 2024-01-08 at 11 22 05@2x](https://github.com/ZzzM/CalendarX/assets/32626686/68a07d2b-d001-453e-87cb-67d2b6d85105)
希望在日历日期的选择上加上双指左右滑动为月份对应的变动。上下滑动为年付的变动，这样不需要每次手动选择月份或者年份

**Comment by ZzzM** [comment]
@oneCatZz 
最新版本可使用快捷键来实现日期切换
    - ⬅️: Last month
    - ➡️: Next month
    - ⬆️: Last year
    - ⬇️: Next year
    - Space: Today
